// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrF1j4cnSBLOrulXRKjsnWXihgFLBpv4',
    appId: '1:1053674822608:web:1e5ec1a1d98c08ebf237d5',
    messagingSenderId: '1053674822608',
    projectId: 'umido-472314',
    authDomain: 'umido-472314.firebaseapp.com',
    storageBucket: 'umido-472314.firebasestorage.app',
    measurementId: 'G-7LXSYWBKBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4MdaSX_GbpSpd0cAov_rCuR5lXe8N9o',
    appId: '1:1053674822608:android:08a64dbce1a013a4f237d5',
    messagingSenderId: '1053674822608',
    projectId: 'umido-472314',
    storageBucket: 'umido-472314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQv3oq2HjvV5kJXme7VV1mXH5fhA58dk',
    appId: '1:1053674822608:ios:6dadf71accd5503bf237d5',
    messagingSenderId: '1053674822608',
    projectId: 'umido-472314',
    storageBucket: 'umido-472314.firebasestorage.app',
    androidClientId: '1053674822608-fmucscrfdbojfns1ov7ieqk0jkntq4nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.umido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASQv3oq2HjvV5kJXme7VV1mXH5fhA58dk',
    appId: '1:1053674822608:ios:6dadf71accd5503bf237d5',
    messagingSenderId: '1053674822608',
    projectId: 'umido-472314',
    storageBucket: 'umido-472314.firebasestorage.app',
    androidClientId: '1053674822608-fmucscrfdbojfns1ov7ieqk0jkntq4nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.umido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyrF1j4cnSBLOrulXRKjsnWXihgFLBpv4',
    appId: '1:1053674822608:web:7c73d0dd7712744af237d5',
    messagingSenderId: '1053674822608',
    projectId: 'umido-472314',
    authDomain: 'umido-472314.firebaseapp.com',
    storageBucket: 'umido-472314.firebasestorage.app',
    measurementId: 'G-BELPKRT689',
  );
}
